[workspace.package]
description = "A library for working with the UF2 file format."
version = "0.3.0"
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/umi-eng/uftwo"

exclude = ["example.uf2"]

[workspace]
resolver = "2"
members = ["uftwo", "uftwo-tools"]

[workspace.dependencies]
uftwo = { path = "uftwo" }
